server.port=8080

# PostgreSQL 数据源
spring.datasource.url=jdbc:postgresql://10.125.205.180:15432/express_db
spring.datasource.username=omm
spring.datasource.password=123456@Abc
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis-Plus 配置
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.id-type=auto

# JSON 日期格式
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai