server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:15432/express_db
spring.datasource.username=express_user
spring.datasource.password=123456@Abc
spring.datasource.driver-class-name=org.postgresql.Driver