server.port=8080
spring.datasource.url=jdbc:postgresql://10.125.205.180:15432/express_db
spring.datasource.username=omm
spring.datasource.password=123456@Abc
spring.datasource.driver-class-name=org.postgresql.Driver
