-- H2 建表脚本（开发环境自动执行）
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(64)  NOT NULL UNIQUE,
    password    VARCHAR(256) NOT NULL,
    real_name   VARCHAR(32),
    phone       VARCHAR(20),
    student_id  VARCHAR(32),
    role        VARCHAR(32)  NOT NULL DEFAULT 'USER',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS runner (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    real_name       VARCHAR(32)  NOT NULL,
    phone           VARCHAR(20)  NOT NULL,
    student_id      VARCHAR(32)  NOT NULL,
    id_card_front   VARCHAR(512),
    id_card_back    VARCHAR(512),
    status          VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    reject_reason   VARCHAR(256),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id        BIGINT         NOT NULL,
    runner_id           BIGINT,
    station_name        VARCHAR(128)   NOT NULL,
    building            VARCHAR(128)   NOT NULL,
    reward              DECIMAL(10,2)  NOT NULL,
    item_info           VARCHAR(512),
    tracking_number     VARCHAR(64),
    status              VARCHAR(32)    NOT NULL DEFAULT 'PENDING',
    evaluation          INTEGER,
    evaluation_content  VARCHAR(512),
    timeout_at          TIMESTAMP,
    created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
