package com.express.delivery;

import com.express.delivery.entity.OrderAcceptRequest;
import com.express.delivery.entity.OrderConfirmRequest;
import com.express.delivery.entity.OrderPublishRequest;
import com.express.delivery.entity.OrderStatusUpdateRequest;
import com.express.delivery.entity.RegisterRequest;
import com.express.delivery.entity.User;
import com.express.delivery.service.OrderService;
import com.express.delivery.service.UserService;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.util.List;

/**
 * 集成测试：验证全部接口业务逻辑
 * 使用 H2 内存数据库，在测试启动时手动建表
 */
@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class DeliveryApplicationTests {

    @Autowired
    private UserService userService;

    @Autowired
    private OrderService orderService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private static Long userId1;
    private static Long userId2;
    private static Long orderId;

    @BeforeAll
    static void setupTables(@Autowired JdbcTemplate jdbc) {
        // 手动建表（H2 兼容语法）
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username    VARCHAR(64)  NOT NULL UNIQUE,
                password    VARCHAR(256) NOT NULL,
                real_name   VARCHAR(32),
                phone       VARCHAR(20),
                student_id  VARCHAR(32),
                role        VARCHAR(32)  NOT NULL DEFAULT 'USER',
                created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS runner (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id         BIGINT       NOT NULL,
                real_name       VARCHAR(32)  NOT NULL,
                phone           VARCHAR(20)  NOT NULL,
                student_id      VARCHAR(32)  NOT NULL,
                id_card_front   VARCHAR(512),
                id_card_back    VARCHAR(512),
                status          VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
                reject_reason   VARCHAR(256),
                created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS orders (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                publisher_id        BIGINT         NOT NULL,
                runner_id           BIGINT,
                station_name        VARCHAR(128)   NOT NULL,
                building            VARCHAR(128)   NOT NULL,
                reward              DECIMAL(10,2)  NOT NULL,
                item_info           VARCHAR(512),
                tracking_number     VARCHAR(64),
                status              VARCHAR(32)    NOT NULL DEFAULT 'PENDING',
                evaluation          INTEGER,
                evaluation_content  VARCHAR(512),
                timeout_at          TIMESTAMP,
                created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """);
    }

    // ==================== 周一：用户注册 ====================

    @Test
    @org.junit.jupiter.api.Order(1)
    void testUserRegister() {
        RegisterRequest req1 = new RegisterRequest();
        req1.setUsername("testuser1");
        req1.setPassword("123456");
        req1.setRealName("测试用户1");
        req1.setPhone("13900001111");
        req1.setStudentId("20240001");
        User user1 = userService.register(req1);
        Assertions.assertNotNull(user1.getId());
        Assertions.assertNull(user1.getPassword());
        Assertions.assertEquals("USER", user1.getRole());
        userId1 = user1.getId();

        RegisterRequest req2 = new RegisterRequest();
        req2.setUsername("testuser2");
        req2.setPassword("123456");
        req2.setRealName("测试用户2");
        req2.setPhone("13900002222");
        req2.setStudentId("20240002");
        User user2 = userService.register(req2);
        Assertions.assertNotNull(user2.getId());
        userId2 = user2.getId();

        Assertions.assertThrows(RuntimeException.class, () -> userService.register(req1));

        System.out.println("[PASS] 用户注册测试");
    }

    // ==================== 周二：订单发布 ====================

    @Test
    @org.junit.jupiter.api.Order(2)
    void testOrderPublish() {
        OrderPublishRequest req = new OrderPublishRequest();
        req.setPublisherId(userId1);
        req.setStationName("菜鸟驿站");
        req.setBuilding("12号宿舍楼");
        req.setReward(new BigDecimal("5.00"));
        req.setItemInfo("一个快递包裹");
        req.setTrackingNumber("SF1234567890");

        com.express.delivery.entity.Order order = orderService.publish(req);
        Assertions.assertNotNull(order.getId());
        Assertions.assertEquals("PENDING", order.getStatus());
        Assertions.assertEquals(userId1, order.getPublisherId());
        Assertions.assertNotNull(order.getTimeoutAt());
        orderId = order.getId();

        req.setReward(BigDecimal.ZERO);
        Assertions.assertThrows(RuntimeException.class, () -> orderService.publish(req));

        System.out.println("[PASS] 订单发布测试");
    }

    // ==================== 周三：接单 ====================

    @Test
    @org.junit.jupiter.api.Order(3)
    void testOrderAccept() {
        OrderAcceptRequest req = new OrderAcceptRequest();
        req.setOrderId(orderId);
        req.setRunnerId(userId2);

        com.express.delivery.entity.Order order = orderService.accept(req);
        Assertions.assertEquals("ACCEPTED", order.getStatus());
        Assertions.assertEquals(userId2, order.getRunnerId());

        req.setRunnerId(userId1);
        Assertions.assertThrows(RuntimeException.class, () -> orderService.accept(req));

        System.out.println("[PASS] 接单测试");
    }

    // ==================== 周三：状态流转 ====================

    @Test
    @org.junit.jupiter.api.Order(4)
    void testOrderUpdateStatus() {
        OrderStatusUpdateRequest req = new OrderStatusUpdateRequest();
        req.setOrderId(orderId);
        req.setStatus("DELIVERING");
        com.express.delivery.entity.Order order = orderService.updateStatus(req);
        Assertions.assertEquals("DELIVERING", order.getStatus());

        req.setStatus("DELIVERED");
        order = orderService.updateStatus(req);
        Assertions.assertEquals("DELIVERED", order.getStatus());

        req.setStatus("PENDING");
        Assertions.assertThrows(RuntimeException.class, () -> orderService.updateStatus(req));

        System.out.println("[PASS] 状态流转测试");
    }

    // ==================== 周三：订单列表 ====================

    @Test
    @org.junit.jupiter.api.Order(5)
    void testOrderList() {
        List<com.express.delivery.entity.Order> list = orderService.listOrders(userId1, "publisher", null);
        Assertions.assertFalse(list.isEmpty());

        List<com.express.delivery.entity.Order> filtered = orderService.listOrders(userId1, "publisher", "DELIVERED");
        Assertions.assertFalse(filtered.isEmpty());
        filtered.forEach(o -> Assertions.assertEquals("DELIVERED", o.getStatus()));

        System.out.println("[PASS] 订单列表查询测试");
    }

    // ==================== 周四：确认收货 + 评价 ====================

    @Test
    @org.junit.jupiter.api.Order(6)
    void testOrderConfirm() {
        OrderConfirmRequest req = new OrderConfirmRequest();
        req.setOrderId(orderId);
        req.setUserId(userId1);
        req.setEvaluation(5);
        req.setEvaluationContent("送得很快，好评！");

        com.express.delivery.entity.Order order = orderService.confirm(req);
        Assertions.assertEquals("CONFIRMED", order.getStatus());
        Assertions.assertEquals(5, order.getEvaluation());
        Assertions.assertEquals("送得很快，好评！", order.getEvaluationContent());

        req.setUserId(userId2);
        Assertions.assertThrows(RuntimeException.class, () -> orderService.confirm(req));

        System.out.println("[PASS] 确认收货+评价测试");
    }

    // ==================== Spring 上下文加载 ====================

    @Test
    @org.junit.jupiter.api.Order(7)
    void contextLoads() {
        Assertions.assertNotNull(userService);
        Assertions.assertNotNull(orderService);
        System.out.println("[PASS] Spring 上下文加载正常");
    }
}
